# https://github.com/marketplace/actions/go-release-binaries
name: Release Binaries

on:
  workflow_call:
    inputs:
      ldflags:
        description: "Go linker flags"
        required: false
        type: string
      buildflags:
        description: "Go build flags"
        required: false
        type: string
  release:
    types: [created]

jobs:
  release-builds:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux,windows,darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - name: Install X
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #goversion: "https://dl.google.com/go/go1.24.2.linux-amd64.tar.gz"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_flags: ${{ env.buildflags }}
        ldflags: ${{ env.ldflags }}
        retry: 10
        sha256sum: true
        md5sum: false
        overwrite: true
        pre_command: go mod tidy
      env:
        ldflags: ${{ inputs.ldflags }}
        buildflags: ${{ inputs.buildflags }}

